### ISSUE TITLE
Missing deletePublication and deleteSubscription

### ISSUE THREAD

**Issue by elsener** [matchmore/js-sdk#5]
<img width="350" alt="screen shot 2018-06-10 at 13 28 54" src="https://user-images.githubusercontent.com/24521573/41201123-6251319e-6cb2-11e8-89f8-d9316397be25.png">

The sdk (compiled file `matchmore.js` in /build) is not able to call deletePublication or deleteSubscription.

**Comment by lmlynik** [comment]
Should be fixed in 0.7.3
